name: CI

on:
  pull_request:
    branches:
      - default
  push:
    branches:
      - default
  release:
    types: published

jobs:
  build-and-test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    name: Build & Test / ${{ matrix.os }} / Rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      run: rustup install --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Check formatting
      run: |
        rustup component add rustfmt
        cargo fmt -- --check

    - name: Lint with Clippy
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings

  #-----------------------------------------------------------------------------
  publish:
    name: Publish
    if: github.event_name == 'release'

    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        run: rustup install --no-self-update stable && rustup default stable

      - name: Login to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: echo $CARGO_REGISTRY_TOKEN | cargo login

      - name: Publish to crates.io
        run: cargo publish

