name: CI

on:
  pull_request:
    branches:
      - default
  push:
    branches:
      - default
  release:
    types: published

# env:
#   CFLAGS: -Wno-error=implicit-function-declaration

# jobs:
#   #-----------------------------------------------------------------------------
#   test:
#     name: Test

#     runs-on: ubuntu-22.04

#     steps:
#     - uses: actions/checkout@master
#     - uses: actions-rust-lang/setup-rust-toolchain@v1
#     - run: cargo test




# name: Cargo Build & Test

# on:
#   push:
#   pull_request:

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build_and_test:
#     name: Rust project - latest
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         toolchain:
#           - stable
#           - beta
#           - nightly
#     steps:
#       - uses: actions/checkout@v3
#       - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
#       - run: cargo build --verbose
#       - run: cargo test --verbose



jobs:
  build-and-test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]


    name: Build & Test / ${{ matrix.os }} / Rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy, rustfmt
        profile: minimal
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Lint with Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
